lab05/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sign_in/',include("sign_in.urls"))

]

sign_in/urls.py
from django.urls import path 
from .  import views 
app_name ='sign_in'

urlpatterns = [



path("",views.index,name="index"),
path('add',views.add,name="add"),

]

sign_in/models.py
from django.db import models

# Create your models here.

sign_in/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django import forms
from django.urls import reverse


class person:
   

    def __init__(self,usname,pasw):
        self.username=usname
        self.password=pasw




        





class NewTaskForm(forms.Form):
    taskU=forms.CharField(label='username')
    taskP=forms.CharField(label='password')
    



#rfrs
#https://www.geeksforgeeks.org/python-get-first-element-of-each-sublist/
def Extract(lst):
    return [item[0] for item in lst]
    


  

# Create your views here.


def index(request):
#as we discussed , you told me to put note over here.    

# and here we will remove the request.session because we cannot add obj with it .
    if "people" not in request.session:
        request.session['people'] = []

    return render (request,"sign_in/index.html", {
        'people':Extract(request.session['people'])
    }) 




def add(request):

    if request.method=="POST":


        form = NewTaskForm(request.POST)
        

        if form.is_valid():

            username = form.cleaned_data['taskU']
            password = form.cleaned_data['taskP']
            
            p=person(username,password)

#as we discussed , you told me to put note over here.          
# request.session[people].append(p)
            request.session['people']+=[[p.username,p.password]]



            


            return HttpResponseRedirect(reverse("sign_in:index"))

        else:

            return render (request,"sign_in/spage.html",{
        "form": form })


    return  render (request,"sign_in/spage.html",{
        "form":NewTaskForm()})

sign_in/templates/sign_in/index.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'sign_in/index.css' %}">
        <title>hello </title>
    </head>
    <body>
        </h1><a href="{% url 'sign_in:add' %}"> <h1>sign in </h1> </a>

        <h2>Names of registered accounts :</h2>

       <h3> <ul>
            
            {% for name in people %}
                <li>{{name}}</li>
            {% endfor %}

        </ul></h3>

       
        
    </body>


</html>

sign_in/templates/sign_in/spage.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'sign_in/spage.css' %}">
        <title>sign in</title>
    </head>
    <body>
        

        <a href="{% url 'sign_in:index' %}"><h1> View accounts </h1></a>

        <h2>sign in:</h2>
        <form action="{% url 'sign_in:add' %}" method="post">
            {% csrf_token %}


            
           <h3>{{form}}</h3>
            <input type="submit">
        


        </form>
        
    </body>


</html>